### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by DezerteR** [DezerteR/Po-Male-Ka#1]
- [ ] Game state handler
- [ ] Better input handling with key bindings
- [ ] Time profiling tools

**Comment by DezerteR** [comment]
- [ ] calculate some shit in compile time with constexpr
