### ISSUE TITLE
Milestone 1 - enabling

### ISSUE THREAD

**Issue by DezerteR** [DezerteR/Po-Male-Ka#2]
- [x] Event queue
  - [x] start/end battle
  - [x] start/end garage /with battle statistics
- [x] Loading scene
  - [x] fully automated
  - [x] blender exporter
    - [x] exporting materials
    - [ ] PBR painting
- [x] Garage basic functionalities
  - [x] tech tree
  - [x] user settings
  - [x] battle statistics
- [x] Shared fonts
- [x] Simple battle
- [x] Simple rendering
