### ISSUE TITLE
Blender extensions

### ISSUE THREAD

**Issue by DezerteR** [DezerteR/Po-Male-Ka#34]
*PL*
Taak rozszerzenie funkcjonalności blendera o dodatkową zakładkę z właściwościami obiektu byłoby bezcenne. Dodatkowa zakładka, nowe typy obiektów, wyciąganie danych z projektu, ehh.

**TODO:**
- [ ] Typy obiektów:
  - [ ] Pancerz
  - [ ] Kolizyjny
  - [ ] Moduły
- [ ] Zakładka, dostosowana pod konkretny typ
  - [ ] Wybór typu modułu( tu albo w konstruktorze)
  - [ ] Wybór broni i amunicji, ilość amunicji
  - [ ] Ustawianie parametrów pojazdu: HP, etc
  - [ ] Parametry silnika pojazdu
  - [ ] Parmaetry z drzewka technologii

**Comment by DezerteR** [comment]
> https://en.wikibooks.org/wiki/Blender_3D:_Noob_to_Pro/Properties_Window

Dodawanie modułów mogłoby byc nawet jako skrypty spod spacji typu 'add turret'.
A scierzka z danymi do wczytania zapisana w .blend

**Comment by DezerteR** [comment]
scieżkę do repo trzymać w modelu,
zrobić skrypty w stylu: save_map, save_tank, etc.

**Comment by DezerteR** [comment]
extracted to other repo
